import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const monrope = Manrope({
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monrope.className}>
      <body
        className={`${monrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
